steps:
# Build the container image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/jude-406606/gcr.io/jude-406606/github.com', '.']
# Push the container image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/jude-406606/gcr.io/jude-406606/github.com']
# Deploy container image to Cloud Run
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args:
    - 'run'
    - 'deploy'
    - 'test-jude'
    - '--image'
    - 'gcr.io/jude-406606/github.com'
    - '--set-env-vars'
    - 'NODE_ENV=production,DB_HOST=/cloudsql/jude-406606:us-central1:testdbjude,DB_USER=root,DB_PASSWORD=testdbjude,DB_NAME=db_jude,SECRET_KEY="iR0FfMkRs51UaWiaxF1WOtgwwrdaXuQmCJTIa3KmvK2TbH0ERdTpKZBrjug1fbtb",DB_SOCKET_PATH=/cloudsql/jude-406606:us-central1:testdbjude'
    - '--region'
    - 'us-central1'
    - '--platform'
    - 'managed'
    - '--allow-unauthenticated'  # Remove if not needed
    - '--port'
    - '8080'  # Update with your Node.js application port
    - '--memory'
    - '256Mi'  # Update with your preferred memory limit
    - '--cpu'
    - '1'  # Update with your preferred CPU limit
images:
- gcr.io/jude-406606/gcr.io/jude-406606/github.com