# cloudbuild.yaml

steps:
  # Step 1: Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/YOUR_PROJECT_ID/YOUR_IMAGE_NAME:$SHORT_SHA', '.']

  # Step 2: Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/YOUR_PROJECT_ID/YOUR_IMAGE_NAME:$SHORT_SHA']

  # Step 3: Deploy the container image to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'YOUR_SERVICE_NAME'
      - '--image'
      - 'gcr.io/YOUR_PROJECT_ID/YOUR_IMAGE_NAME:$SHORT_SHA'
      - '--region'
      - 'YOUR_REGION'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--set-env-vars'
      - 'NODE_ENV=production,DB_NAME=db_jude,DB_USER=root,DB_PASSWORD=testdbjude,DB_SOCKET_PATH=jude-406606:us-central1:testdbjude'
      - '--port'
      - '8080'
      - '--memory'
      - '256Mi'
      - '--cpu'
      - '1'
